### ISSUE TITLE
Good for debugging

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#1]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L126

I see you've added some logging in various places, even when there is nothing being done. Especially good to make sure **something** is happening!

Good!

**Comment by NucciTheBoss** [comment]
Thanks John!
