### ISSUE TITLE
Refactor to eliminate duplicate code

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#11]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L173-L184

You could do ```tmp_token or token``` to select and use one ```update()```.

**Comment by NucciTheBoss** [comment]
I'll play around with that and see what I get. Could probably change to the following:

```python
r.data[self.unit].update( 
     { 
         "token": self.dumps(tmp_token) if tmp_token is not None else self.dumps(token) 
     } 
)
```
Also, the comma above is extraneous.

**Comment by j4m-can** [comment]
Or even:
```
self.dumps(tmp_token if tmp_token is not None else token)
```

or possibly old-school:
```
self.dumps(tmp_token or token)
```

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
