### ISSUE TITLE
get_relation() can be used, too

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#15]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L160

The ```self.model.get_relation(relname)``` can be used, too.

**Comment by NucciTheBoss** [comment]
The more you know! This is another snippet that I had pulled from the sdk documentation, but I added the [0] since I knew I only needed one relation.
