### ISSUE TITLE
Why check for app?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#16]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L140

Under what circumstances would a unit belonging to the peer relation ever **not** have an app?

You mentioned that you encountered such a case. Can you recall/reproduce it? I would think that to be a bug if so.

**Comment by NucciTheBoss** [comment]
To be honest, I just used what I saw in the [Handling relation data from other hooks](https://juju.is/docs/sdk/relations#heading--handling-relation-data-from-other-hooks-example) example in the Juju documentation. I could probably remove this check in the next update.

**Comment by j4m-can** [comment]
So that is when dealing with relations outside of a relation event/hook ([Handling relation data from non-relation hooks](https://juju.is/docs/sdk/relations#heading--handling-relation-data-from-other-hooks-example)). When in a peer relation event, event.relation (or from get_relation()), the units **must** be from the same app.

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
