### ISSUE TITLE
Alias would be helpful

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#17]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L117-L122

You used an alias for ```max_passes``` and ```delay```. Using one for ```self._stored.bucket``` would have made things more readable/shorter. It is used 4 times.

**Comment by NucciTheBoss** [comment]
I can do this. I just used it since `_stored` is already used, but I can use a shorter alias name to reduce the amount of characters.

**Comment by NucciTheBoss** [comment]
Fixed in the latest update.
