### ISSUE TITLE
Line width

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#20]
https://github.com/NucciTheBoss/charming-exercises/blob/30e9ffd7cc52f0bb63e333662a8d0bca19382415/hot-potato/src/charm.py#L85-L88

This does not span >88 columns. Did you format it multiline by hand?

**Comment by NucciTheBoss** [comment]
Yes, I did manually format. I have yapf installed, but I haven't tested it yet. This would be a good time to do so!
