### ISSUE TITLE
Misnomer?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#5]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L69

```_AdvancedBucket``` is not actually a bucket but a codec. And in this case is used with bucket data.

Probably clearer if ```json.dumps()``` and ```json.loads()``` used instead. Unless, you would want to drop in an alternate! So apart from the name, it works.

**Comment by NucciTheBoss** [comment]
That makes sense, I just wanted to have a `dumps` and `loads` method to make my life easier when reading/writing data to the relation data bucket. I can just refactor the name to be: `_Codec`.

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
