### ISSUE TITLE
+ is not required

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#6]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L45-L50

Not wrong, but FYI, "+" is not needed for continuation in certain contexts (e.g., argument).

E.g.,
```
x = ("hi"
"there"
"world")
```
Gives ```hithereworld```.

**Comment by NucciTheBoss** [comment]
The more you know!

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
