### ISSUE TITLE
Use default

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#7]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L31

Why not ```delay = kwargs.get("delay", 0)```?

**Comment by NucciTheBoss** [comment]
Outing myself here, but I had no idea that was an option :clown_face:. I sourced the method from a previous implementation I did for when I was writing a custom method for printing the version of a program: https://gist.github.com/NucciTheBoss/0128aa0aceded4fa973658906046824b. I used the above method to check if the dev had specified a figlet banner to print out as well.
