### ISSUE TITLE
Overly complex

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#8]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L24-L66

I understand what you were wanting to do from our discussion. At this point, the ```Forward.forward()``` seems overly complex to simply pick up the token from the **last** unit and have the matching one act on it.

**Comment by NucciTheBoss** [comment]
Hmm. It does not feel too complex to me, but that is probably because I am the one who wrote the method. Which part seems too complex? I mostly just used recursion so that I would not lose time sending the data from the target unit to another unit, and then back again to the target unit so that I could trigger the `RelationChanged` event handler in the target unit.

**Comment by j4m-can** [comment]
When you post something to a bucket, it goes to the controller to be saved. At which point, an event is sent to **all** units in the relation. I.e., broadcast to all relation members. There is no way to restrict this. It is impossible to implement true point-to-point communication with relations. It can be simulated using convention, but even that does not prevent the event broadcast. Every unit gets a notification, although peeking into the bucket is optional.

So, if you just post to the ```self.unit bucket```, all the other units will need to check that unit's bucket. And whichever unit determines it should respond, it should.

**Comment by NucciTheBoss** [comment]
So I would just update the bucket then? I found that the unit updating the bucket would not capture event and thus would not run `_on_<relation>_changed(self, event)`. Do you have an example? That might help clear up my confusion.

**Comment by j4m-can** [comment]
Yes, just update the bucket.

Now, if the potato is being handed off from a unit to itself, then:
* you need to handle that locally, immediately and possibly without an event
* trigger an event which the unit will be guaranteed to get (this is what David was mentioning about the ```emit()```)
* or find another way ... :)

My way is a bit different from your's which I'll share once we're done.

**Comment by NucciTheBoss** [comment]
I feel think that is what I am doing here? I use recursion to rerun the function if the unit is handing the token off to itself. If the token is being handed off to a new unit, it returns the token which is then used to update the bucket.

**Comment by j4m-can** [comment]
Ok. I see it now.

SGTM!

**Comment by j4m-can** [comment]
Then it is not overly complex!

**Comment by NucciTheBoss** [comment]
Sweet! Thank you!
