### ISSUE TITLE
Loss of accuracy of accumulated time

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#9]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L54

Using ```round()``` causes a significant loss of precision and actually introduces error. > x.5 rounds up, which is up to just under +0.5 off, while <= x.5 rounds down which is up to -0.5 off.

What if the delta between each update was <= 0.5? What would ```time_elapsed``` be? The issue doesn't go away even if the delay is >=1s.

You are better off keeping accurate counts and tweaking displays that favoring display and lossing information.

**Comment by NucciTheBoss** [comment]
Sounds good. I can fix this up pretty quickly, but I will need to import the `numbers` module to insure the the float calculations are accurate.

**Comment by j4m-can** [comment]
I would just use the float and use string formatting when you need to display. The kooky float precision issues will be hidden by the formatting.

E.g.,
```
f'{1.2345:.2f}'
```

**Comment by NucciTheBoss** [comment]
Fixed in the latest update.
